### PR TITLE
GHC 8.0 support

### PR DESCRIPTION
**Pull request by borsboom**

### CODE REVIEW

**Comment by tmhedberg** [comment]
Thanks.

**Comment by borsboom** [comment]
Can we get a new release to Hackage (or just loosen the bounds in the existing package's metadata) for this?

**Comment by tmhedberg** [comment]
Yes, done. I've uploaded v1.2.8 to Hackage. Thanks for the reminder.

**Comment by borsboom** [comment]
Thanks!  I've made a PR to add `here` back to Stackage: https://github.com/fpco/stackage/issues/1511

**Pull request merged**
