### PR TITLE
GHC 7.10 support

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by tmhedberg** [comment]
Thanks!

Were you actually able to get this to build with GHC 7.10? I still can't build it because here depends on haskell-src-meta, which depends on base < 4.8, but the GHC 7.10 version of base is 4.8, so the dependency can't be satisfied.

**Comment by tmhedberg** [comment]
For reference:

```
$ cabal install --with-ghc=$HOME/src/ghc-7.10.0.20150123/inplace/bin/ghc-stage2 --with-ghc-pkg=$HOME/src/ghc-7.10.0.20150123/inplace/bin/ghc-pkg
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: HTTP-4000.2.19/installed-f2f... (user goal)
trying: here-1.2.6 (user goal)
next goal: haskell-src-meta (dependency of here-1.2.6)
rejecting: haskell-src-meta-0.6.0.8, 0.6.0.7, 0.6.0.6, 0.6.0.5, 0.6.0.4,
0.6.0.3 (conflict: HTTP => base==4.8.0.0/installed-inp..., haskell-src-meta =>
base>=4.2 && <4.8)
rejecting: haskell-src-meta-0.6.0.2, 0.6.0.1, 0.6 (conflict: HTTP =>
base==4.8.0.0/installed-inp..., haskell-src-meta => base>=4.2 && <4.7)
rejecting: haskell-src-meta-0.5.1.2, 0.5.1.1, 0.5.1, 0.5.0.3, 0.5.0.2, 0.5,
0.4.0.2, 0.4.0.1, 0.4, 0.3, 0.2, 0.1.1, 0.1.0, 0.0.6, 0.0.5, 0.0.4, 0.0.3.1,
0.0.3, 0.0.2, 0.0.1, 0.0.0 (conflict: here => haskell-src-meta==0.6.*)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by bgamari** [comment]
Yes I've been able to build this against various unreleased dependecy versions. `haskell-src-meta` has been updated upstream although hasn't been released to Hackage.

**Comment by tmhedberg** [comment]
Thanks, I was able to build it with the latest upstream versions of haskell-src-meta and th-expand-syns from GitHub.

**Pull request merged**
